# Generated by Django 5.0.7 on 2025-05-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('proteins', 'proteins'), ('vitamins', 'vitamins'), ('creatines', 'creatines'), ('amino acids', 'amino acids'), ('pre-workout', 'pre-workout')], max_length=30)),
            ],
        ),
    ]
